language: python
python:
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
# command to install dependencies
virtualenv:
  system_site_packages: true
before_install:
   #Uses miniconda installation of scientific python packages instead of building from source
   #or using old versions supplied by apt-get. Source: https://gist.github.com/dan-blanchard/7045057
   - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
   - chmod +x miniconda.sh
   - ./miniconda.sh -b
   - export PATH=/home/travis/miniconda3/bin:/home/travis/miniconda/bin:$PATH
   - conda update --yes conda
   - sudo apt-get install -qq build-essential
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip
  - pip install snakemake cookiecutter
  - git clone https://github.com/EnvGen/cookiecutter-binning-project-demo.git
  - cd cookiecutter-binning-project-demo
  - chmod +x run_all.sh
# command to run tests
script: ./run_all.sh

branches:
  only:
    - master
    - develop
